spring.application.name=sistema_barbearia
spring.datasource.url=jdbc:mysql://localhost:3306/barbearia
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true